#!/bin/sh
# Command line utility not actually packaged with the clojar itself. Will
# eventually be either deleted or placed within a streamparse project directory
# upon quickstart.

usage='sparsej

The streamparse command line interface for JVM/Thrift interop with Storm.

Usage:
    sparsej <command> [options]

Commands:
    sparsej list    For listing topologies on a running cluster.
    sparsej kill    For killing topologies by name.
    sparsej run     For running local topologies.
    sparsej submit  For submitting topologies to remote clusters.

Examples:
    sparsej list --json
    sparsej kill mytopology

To see help on a given command type:
    sparsej <command> [-h | --help]
'

if [ "$1" == "list" ]; then
    lein run -m streamparse.commands.list/-main ${*:2}
elif [ "$1" == "kill" ]; then
    lein run -m streamparse.commands.kill/-main ${*:2}
elif [ "$1" == "run" ]; then
    lein run -m streamparse.commands.run/-main ${*:2}
elif [ "$1" == "submit" ]; then
    lein run -m streamparse.commands.submit_topology/-main ${*:2}
else
    echo "$usage"
fi