maintainer       "Andrew Montalenti"
maintainer_email "git@amontalenti.com"
name			 "streamparse"
license          "Apache 2.0"
description      "Installs/Configures streamparse"
version          "0.1"
