source "https://rubygems.org"

gem "rake"
gem "berkshelf"
gem "strainer"
gem "rubocop"
gem "chefspec", ">=3.0.0"
gem "foodcritic", ">=3.0.0"
gem "test-kitchen"
gem "kitchen-vagrant"
gem "thor-scmversion", "~> 1.7"
